export const AddjobConstants ={

    JOBS_REQUEST: 'JOBS_REQUEST',
    JOBS_SUCCESS: 'JOBS_SUCCESS',
    JOBS_FAILURE: 'JOBS_FAILURE',
    EDIT_JOBS_REQUEST: 'EDIT_JOBS_REQUEST',
    EDIT_JOBS_SUCCESS: 'EDIT_JOBS_SUCCESS',
    EDIT_JOBS_FAILURE: 'EDIT_JOBS_FAILURE',
    UPDATE_JOBS_REQUEST: 'UPDATE_JOBS_REQUEST',
    UPDATE_JOBS_SUCCESS: 'UPDATE_JOBS_SUCCESS',
    UPDATE_JOBS_FAILURE: 'UPDATE_JOBS_FAILURE',
};