export const ApplyJobsConstants ={

    APPLY_JOBS_REQUEST: 'APPLY_JOBS_REQUEST',
    APPLY_JOBS_SUCCESS: 'APPLY_JOBS_SUCCESS',
    APPLY_JOBS_FAILURE: 'APPLY_JOBS_FAILURE',
    APPLIED_JOBS_REQUEST: 'APPLIED_JOBS_REQUEST',
    APPLIED_JOBS_SUCCESS: 'APPLIED_JOBS_SUCCESS',
    APPLIED_JOBS_FAILURE: 'APPLIED_JOBS_FAILURE',
    UPDATE_STATUS_REQUEST: 'UPDATE_STATUS_REQUEST',
    UPDATE_STATUS_SUCCESS: 'UPDATE_STATUS_SUCCESS',
    UPDATE_STATUS_FAILURE: 'UPDATE_STATUS_FAILURE'
};

